# Generated by Django 4.0.6 on 2022-08-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('showingTime', models.TimeField()),
                ('bookingClass', models.CharField(max_length=100)),
                ('paymentMethod', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='emailSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='movies',
            name='posterURL',
            field=models.URLField(),
        ),
    ]
