# Generated by Django 4.0.6 on 2022-08-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0004_bookings_emailsubscribers_alter_movies_posterurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowingTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('movieName', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(decimal_places=3, max_digits=99)),
            ],
        ),
        migrations.AlterField(
            model_name='bookings',
            name='showingTime',
            field=models.CharField(max_length=25),
        ),
    ]
