# Generated by Django 4.0.6 on 2022-08-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0005_showingtimes_alter_bookings_showingtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emailSubscribers',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='showingTime',
            field=models.CharField(max_length=50),
        ),
    ]
