# Generated by Django 4.0.6 on 2022-08-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0006_delete_emailsubscribers_alter_bookings_showingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='bookingClass',
            field=models.CharField(choices=[('economy', 'Economy'), ('first class', 'First Class')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='paymentMethod',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit Card')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='showingTime',
            field=models.CharField(choices=[('13:00:00', '1:00'), ('14:00:00', '2:00')], max_length=50),
        ),
    ]
