# Generated by Django 4.0.6 on 2022-08-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0009_remove_showingtimes_moviename_showingtimes_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showingtimes',
            name='movie',
            field=models.ForeignKey(default='ho', on_delete=django.db.models.deletion.CASCADE, to='theater.movies'),
        ),
    ]
