# Generated by Django 4.0.6 on 2022-08-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0012_alter_showingtimes_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='showingTime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theater.showingtimes'),
        ),
    ]
