# Generated by Django 4.0.6 on 2022-09-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0013_alter_bookings_showingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='showingTime',
            field=models.TimeField(),
        ),
    ]
